### ISSUE TITLE
115.2 Order status updates

### ISSUE THREAD

**Issue by freeaanzee** [OxfamFairTrade/oft#3]
Per XML every 30 minutes. Also containing orders not put in via webshop. Watch out for empties and items not (available) in BestelWeb. Open orders and orders closed on that day.

**Comment by freeaanzee** [comment]
Exports uit Odisy zijn niet event-based, dus we ontvangen gewoon alle orderlijnen die de afgelopen bv. 4 weken gewijzigd werden in een CSV en registreren alles in de weborders.

De webshop behandelt qua orders:
- N: default
- CH: geschenkencheques
- B: leeggoedretour
- RL: toegevoegde producten uit ander magazijn 

Correctieve orders DF (te regelen met KD) en verhuurorders V (te raadplegen in facturatie) negeren we. De orders hebben de minimum orderstatus van alle onderliggende orderlijnen.

De webshop behandelt qua retours:
- Type 1: echte retours die fysiek opnieuw ingeboekt worden en vervolgens gecrediteerd
- Type 2: breuken en kwaliteitsissues die meteen gecrediteerd worden

Deze tonen we als informatieve tekstorders onder 'Mijn account'.

**Comment by Oostkustpolders** [comment]
Probleempjes om het via de Reporter te doen. Door de manier waarop het datamodel in Odisy in elkaar zet, moet ik gebruik maken van 4 datasets (open orders, open credit, recent gefactureerd en recent gecrediteerd). In de export naar .csv komen alle datasets er naast elkaar uit, in plaats van onder elkaar. Dus ofwel maak ik 4 rapportjes, ofwel probeer ik het in .NET? Ik kan dan ook voor .xml gaan, misschien eleganter...

**Comment by freeaanzee** [comment]
Gezien de - in principe - tijdelijke aard van dit systeem zou ik zeggen: doe dan maar gewoon 4 aparte rapportjes? Maar ik hou je niet tegen om in .NET te duiken!

**Comment by freeaanzee** [comment]
De registratie van achteraf toegevoegde producten (o.a. paletten) staat klaar en wordt tijdens de kerstvakantie live gezet. De referenties 'LDAFH' (bij een afhaling) en 'p' (???) worden daarbij geskipt.

Het overzichtsscherm in de back-end met alle orders toont in rood de afwijkingen tussen Odisy en BestelWeb. Nog toe te voegen: check op gewijzigd leveradresnummer. De Odisy-data kan de BestelWeb-data ook automatisch overschrijven, maar dan moeten we zeker zijn dat KD al de nodige aanpassingen gedaan heeft (routecode, leverdatum, ...) dus daarvoor wacht ik liever op de webservices.
