### ISSUE TITLE
115.3 OFT article data import

### ISSUE THREAD

**Issue by freeaanzee** [OxfamFairTrade/oft#4]
Item master data, prices and stock levels (take in account existing orders, to be subtracted from available stock). Some data will be maintained in webshop directly (descriptions, allergens, ingredients, diets) by catmans, as is.

If an item has to go on sale but doesn't exist in BestelWeb yet: automatically create product with basic Odisy information (name, SKU, consumer price) in all languages. This will be standard for most non-food items.

**Comment by freeaanzee** [comment]
We aren't ready yet for a price system with client-based discounts, applied to the consumer price, so we still have to import explicit prices for OWW / MDM clients. B2B groups can be added according to needs.

Promotions will silently appear, maybe add a checkbox or do a cross calculation from the consumer price to detect promotions?

**Comment by freeaanzee** [comment]
- STEH (stock eenheid) overal vervangen door VKEH (verkoop eenheid), ook in de kolom-hoofdingen. Met de niet-voeding erbij is de normale ST-OMPAK-PAL structuur geen garantie, dus alle omrekenfactoren, voorraad, prijzen etc… zijn maal een factor gedaan om altijd op VKEH uit te komen. Indien er geen VKEH bestaat, werd STEH genomen.
- Filter is nu alle artikels die in odisy op verkoopbaar staan exclusief deze groepen: crafts/solidair (zijn er toch geen meer), verpakkingsmateriaal (voor de productie van eindproducten), huurmateriaal, colli en dummy/virtuele artikels.
- BTW: 6% staat gemarkeerd als ‘voeding’, zoals het al was maar lijkt wel beetje raar want sommige niet-voeding is ook 6% terwijl alcohol aan 21% is.
- Ene hele rare is artikel 00850 (schoteltje+kopje), dit is zelf geen voorraadartikel maar vertaalt zich in odisy als 2 picklijnen van 00848 schoteltje en 00849 kopje. Wordt verder per stuk in voorraad gehouden maar verkocht per 24. Voor de voorraad heb ik hard coded de kleinste voorraad van 00848/00849 genomen en gedeeld door 24.
- Assortimenten: ik heb uiteindelijk 4 nieuwe velden in odisy aangemaakt en daar ‘yes’ of ‘no’ ingevuld. Assortimenten zijn OWW, MDM, B2BNL (enkel voor nederlandstalige B2B, FTO heeft bijvoorbeeld geen frans op verpakking), B2BFR (2e B2B assortiment).

**Comment by freeaanzee** [comment]
Ik mis nog de productcategorieën voor de automatische aanmaak van producten die niet door de catmans aangemaakt werden. Dat mag een soort taxonomiecode zijn die ik vervolgens kan mappen aan een hoofd/subcategorie.

De velden CU UOM FR, CU UOM EN, VKEH UOM FR en VKEH UOM EN mogen weer verwijderd worden. Eenheden worden niet als expliciete metadata toegevoegd aan elk individueel, maar als een attribuut dat vervolgens eenmalig vertaald wordt in de site zelf.

Om consequent te zijn gebruiken we misschien best 'yes' voor alle true-ish waarden (i.p.v. 'ja', 'aan', ...) en 'no' voor het andere geval. De BTW-schalen zal ik op mijn beurt hernoemen naar 'standard' (21%), 'reduced' (6%) en 'zero' (0%) in de site.

**Comment by Oostkustpolders** [comment]
aangepast
[B2CImport3.zip](https://github.com/OxfamFairTrade/oft/files/3057951/B2CImport3.zip)

**Comment by freeaanzee** [comment]
Assortimentskolommen samengevoegd tot één kolom met pipes.
